export const RESTART_AUTH_RESPONSE = 'RESTART_AUTH_RESPONSE';
export const LOADING = 'LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const CODE_ERROR = 'CODE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const LOAD_IP_ADDRESSES_SUCCESS = 'LOAD_IP_ADDRESSES_SUCCESS';
export const LOAD_IP_ADDRESSES_ERROR = 'LOAD_IP_ADDRESSES_ERROR';

export const ADD_IP_ADDRESS_SUCCESS = 'ADD_IP_ADDRESS_SUCCESS';
export const ADD_IP_ADDRESS_ERROR = 'ADD_IP_ADDRESS_ERROR';